--liquibase formatted sql

--changeset skomarov:1 labels:v0.0.1
CREATE TYPE "card_visibilities_type" AS ENUM ('PUBLIC', 'PRIVATE');

CREATE TABLE "cards" (
	"id" bigint primary key generated by default as identity,
	"title" text not null constraint cards_title_length_ctr check (length(title) < 128),
	"message" text constraint cards_description_length_ctr check (length(message) < 256),
	"description" text,
	"owner_id" bigint not null,
	"genre" text not null constraint cards_genre_length_ctr check (length(genre) < 64),
	"latitude" double precision not null,
	"longitude" double precision not null,
	"visibility" card_visibilities_type not null,
	"lock" text not null constraint cards_lock_length_ctr check (length(lock) < 64)
);

CREATE INDEX cards_geo_info_idx on "cards" using btree ("latitude", "longitude");
