#---------------------------------- For Kotlin Native --------------------------------
FROM ubuntu
COPY ./music-map-be/music-map-app-ktor/build/bin/linuxX64/releaseExecutable/music-map-app-ktor.kexe /musicmap
ENTRYPOINT ["/musicmap"]